version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: ogabriel/first_try:first
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
