# COMPOSE_PROJECT_NAME=test docker-compose -f docker-compose.test.yml up
services:
  foo:
    image: busybox
    environment:
      - COMPOSE_PROJECT_NAME
    command: echo "I'm running ${COMPOSE_PROJECT_NAME}"
